### ISSUE TITLE
changes needed in network dns-zone record-set create command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1777]
__Sample command used__: network dns-zone record-set create -y A -l 300 rg1 cli.com test

* Checks for existence of the DNS zone.  There is no need…if the zone doesn’t exist, and error will be returned and this can be passed back to the user.  This will make the command faster and the audit logs easier to understand.

* Checks for existence of the record set.  There is no need…instead, use ‘if-none-match: *’ to guarantee that a new record set is created.  This will be faster, simplify logs and provide better concurrency protection.  See similar feedback for ‘azure network dns-zone create’.

* TTL parameter enforces a range 1…255.  This is wrong.  Valid range is 0…2,147,483,647.  Applies also to ‘azure network dns-zone record-set set’.

* All the other record-set commands allow the record type to be passed as a parameter at the end of the line, after the record set name, without the ‘—type’ or ‘-y’ prefix.  I suggest we do the same here.  I.e. allow ‘azure network dns-zone record-set –l 300 rg1 cli.com test A’.

tagging @jtuliani here

**Comment by HimanshuBri** [comment]
Following issues are fixed & working fine 
1. Checks for existence of the DNS zone
2. TTL parameter enforces a range 1…255. 
3. All the other record-set commands allow the record type to be passed as a parameter at the end of the line, after the record set name, without the ‘—type’ or ‘-y’ prefix

But It is still checking for existence of the record set.That issue is still there

<pre>
<code>
C:\May\18M\azure-xplat-cli-dev-azure-bug-1777>node bin/azure network dns-zone record-set create -l 214743647 armresgrp181M arm.dnszoneprod1 test2 A
^C
C:\May\18M\azure-xplat-cli-dev-azure-bug-1777>node bin/azure network dns-zone record-set create -l 214743647 armresgrp181M arm.dnszoneprod1 test2 A
info:    Executing command network dns-zone record-set create
+ Creating DNS record set "test2"
+ Looking up the DNS record set "test2"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp181M/providers/Microsoft.Network/dnszones/arm.dnszoneprod1/A/
test2
data:    Name                            : test2
data:    Type                            : Microsoft.Network/dnszones/A
data:    Location                        : global
data:    TTL                             : 214743647
info:    network dns-zone record-set create command OK


</code>
</pre>

**Comment by roman-boltunov** [comment]
@HimanshuBri could you recheck this please?

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
