### ISSUE TITLE
changes needed in network dns-zone record-set show command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1781]
*  No need to prefix ‘Record1’, ‘Record2’ etc on each line of actual record data, please remove these prefixes.
* Labels must be exact match to existing terminology elsewhere in CloudDNS.  For example, for NS records, the record data is referred to as ‘nsdname’, so we should use the same label in the CLI output.  
See REST API on MSDN for full list (https://msdn.microsoft.com/en-us/library/azure/mt130627.aspx)

tagging @jtuliani here

**Comment by anuchandy** [comment]
@jtuliani 

Regarding second point, the show command output can be one of the following format. 

1. in table format (Name : Value) 
2. in json format (if -json option in given).

When we show output in json format it exactly looks like what server returns in response body, i.e. similar to msdn doc.

When we show output in table format, the guideline is to have readable label, for example in case of VM show result, its needs to be

'Windows Configuration' instead of 'windowsconfiguration' or
'Operating system type' instead of 'operatingsystemtype'.

If you are suggesting to use same key as json, then it needs to be changed across the CLI. But the point i am trying to bring up is table output should be "readable" while json output matches exactly what server returns. This is how PowerShell Azure tool shows output.

Adding @kmouss  to comment, we might want to standardize and be consistent on how we show output in table and json format across CLI.

**Comment by jtuliani** [comment]
Agree with readable output, if that's the CLI-wide policy.  Please provide a mapping from JSON name -> readable name across all DNS types for review.

**Comment by HimanshuBri** [comment]
Following issues seems to be fixed 
1. No need to prefix ‘Record1’, ‘Record2’ etc on each line of actual record data, please remove these prefixes.
![1781](https://cloud.githubusercontent.com/assets/10084788/7681568/cfabd7d0-fd8e-11e4-9495-706d64a8eb8c.PNG)

**Comment by anuchandy** [comment]
@HimanshuBri thank you.

@jtuliani please see the mapping below:

DNS Zone
--------

id -> Id
name -> Name
type -> Type 
location -> Location 
numberOfRecordSets -> Number of record sets);

DNS Zone Recordset
------------------

aRecord -> A Records
  ipv4Address -> IPv4 address

aaaaRecords -> AAAA records
  ipv6Address -> IPv6 address

cnameRecord -> CNAME record
  cname -> CNAME

mxRecords -> MX records
  preference -> Preference
  exchange -> Exchange

nsRecords -> NS records
  nsdname -> Domain name

srvRecords -> SRV records
  priority -> Priority
  weight -> Weight
  port -> Port
  target -> Target

txtRecords -> TXT records
  Text

soaRecord -> SOA record
  email -> Email 
  expireTime -> Expire time
  host -> Host 
  serialNumber -> Serial number 
  minimumTtl -> Minimum TTL
  refreshTime -> Refresh time 
  retryTime -> Retry time 

ptrRecords -> PTR records
  ptrdname ->  Ptrd name

**Comment by jtuliani** [comment]
All fine, except please change:

numberOfRecordSets -> Number of record sets (I assume there was just a typo there)
exchange -> Mail exchange
nsdname -> Name server domain name
ptrdname -> PTR domain name

Thanks!

**Comment by anuchandy** [comment]
@jtuliani thank you for reviewing.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed, fixed
