### ISSUE TITLE
AD Accounts with MFA enabled don't seem to be able to interactively login, even with app passwords 

### ISSUE THREAD

**Issue by albertoperdomo** [Azure/azure-xplat-cli#1935]
I'm able to login via `azure login -u user@domain.com`
If I enable MFA for the account, logging in does not work because MFA with 1-time password is not supported.

I've tried creating an app password in the MFA configuration settings and using that, but it's also failing to login.

```
Error: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password\r\nTrace ID: 20ee7805-e45a-4ad4-823c-2fc712344a3b\r\nCorrelation ID: 369af279-6713-4176-b839-cf29e25dcc3e\r\nTimestamp: 2015-07-17 13:44:47Z","error_codes":[70002,50126],"timestamp":"2015-07-17 13:44:47Z","trace_id":"20ee7805-e45a-4ad4-823c-2fc712344a3b","correlation_id":"369af279-6713-4176-b839-cf29e25dcc3e","submit_url":null,"context":null}
```

I know there is an option to use certificate authentication, but it would be useful to take advantage of MFA & app passwords in CLI.

**Comment by devigned** [comment]
Unfortunately, this is expected with MFA and Azure CLI. We are enabling login for MFA enabled environments very soon.

Currently, you can create a service principal though Azure PowerShell or the Azure Portal. This service principal will be able to login via `azure login --service-principal`. To create a service principal via the portal, see: https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/. To assign the service principal contributor role or other RBAC roles see: https://azure.microsoft.com/en-us/documentation/articles/role-based-access-control-configure/.

Certificate authentication is currently only available for Azure Service Management (Azure rest api v1). Azure Active Directory authentication is required for Azure Resource Manager (Azure rest api v2).

**Comment by infosatheesh2020** [comment]
I had an organizational account with MFA enabled, but login worked fine with CLI (0.9.6) until yesterday (both for asm and arm mode). But it is not allowing to login today.

error:   Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50079: Strong authentication enrollment (proof-up) is required.\r\nTrace ID: 4510b277-97b7-4fdf-8864-b35d2b1d2db4\r\nCorrelation ID: 8f4b18db-1a94-45b8-8374-7b0ff1816bb9\r\nTimestamp: 2015-08-06 10:11:56Z","error_codes":[50079],"timestamp":"2015-08-06 10:11:56Z","trace_id":"4510b277-97b7-4fdf-8864-b35d2b1d2db4","correlation_id":"8f4b18db-1a94-45b8-8374-7b0ff1816bb9","submit_url":null,"context":null}

I'm not able to figure out why. Also, do we have any option of using CLI in arm mode now?

**Comment by devigned** [comment]
Perhaps your refresh token was still good from an earlier authentication. MFA is not currently supported via CLI. We are working to fix this, but until then, please use a service principal. See: http://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/

**Comment by infosatheesh2020** [comment]
Hi, I tried to set service-principal login, but not fully working.

I have followed the steps in managing a local AD adding the new application, and granting all the rights to the application. But when i login to that application, my existing subscription details are not listed.

azure login --service-principal 
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Username: c9f90ceb-fc4d-4db2-ac38-d926085d1035
Tenant: 0710cdcc-2ef8-4d9c-9889-56e7bdc3156d
Password: ********************************************
|info:    No subscriptions found for this account                              
+
info:    login command OK


I have an MS organizational account with @mds.microsoft.com domain with MFA enabled, and I don't have any control of organizational AD for my subscription, nor any applications I was tagged. So I created a new local application in a newely created local AD and When I try to add permissions to existing application (to get ownership of my existing organizational subscription), my organizational apps are not listed. Is there any way to use ARM using service principal (Currently creating new apps in new AD don't solve my problem since I don't have access to existing application)

**Comment by romangromov** [comment]
Hi @devigned, same issue here for me: when I login to newly created application using `ClientID`, 'Key' and 'Tenant' provided in `Management Portal`, my existing subscription details are not listed, so I can't perform any king of commands with Xplat-CLI:

**Comment by devigned** [comment]
It sounds like the Service Principal was either not provided rights to manage the service management api or is not in a role to manage any resources in the resource management apis. Please verify you have provided the account the correct rights and role.

@yugangw-msft and @amarzavery what do you think?

**Comment by devigned** [comment]
@infosatheesh2020 yes, service principal can be used for ARM. In fact, for automation scenarios, it's what you should use.

**Comment by infosatheesh2020** [comment]
@devigned The problem is that I am not able to view the existing applications in my current organizational subscription. When I try to create new local AD, and create applications in it, I'm not able to access resources in my parent subscription (atleast i don't have access from new application created to add existing applications from parent subscription)

**Comment by yugangw-msft** [comment]
@romangromov
The subscription doesn't show up till someone grant the service-principal access to some resources underneath, which is mostly accomplished by using "role assignment create" command. After that related subscriptions will show up

**Comment by yugangw-msft** [comment]
@infosatheesh2020
If you are talking about the "active directory application" and be able to view it, make sure the service principal has read access to the AD graph. You can configured it in the portal. This specific scenario has nothing to do with the subscriptions.
Once you have provisioned the application in the tenant, you will get related service principal id and key, which you can log in with that. But to access individual azure resources, you still need to login as an account with enough permission to grant the access so called RBAC.
Hope this helps.

**Comment by sondreb** [comment]
@devigned If it is already very well known that MFA is not supported with azure-cli (and PowerShell), how come this is not communicated anywhere other than on this issue here on GitHub?

It drives me nuts having to waste hours on this when it could have been communicated in a dozen places on MSDN and other places.

Why would you tell customers to disable multi-factor authentication on their accounts that access Microsoft Azure resources? That's insanely stupid and dangerous to do.

Please also fix the error messages, because if a user with MFA login with regular password, the error in log is:

**"AADSTS50076: Application password is required.**

Then when using app password, it is:

**"AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password**

And then your customers are picking their hairs and biting nails, while manually entering password, doing tricky copy paste operations to ensure that the input in the console is absoltely correct. But obviously to no success, since it is known not to work.

The solution with service principle is a huge walk-around if someone wants to do some minor management of resources with command tools. And in either case, I don't like having accounts without MFA, which a service principle in reality is, with a huge amount of account access.

**Comment by romangromov** [comment]
@sondreb :+1: agree, I've spent my day trying to figure out this issue ...

**Comment by romangromov** [comment]
@yugangw-msft @devigned thank you guys for your help, finally get it to work with a few Power-Shell based cmdlets:

```PowerShell
Get-AzureRoleDefinition Owner
$service = Get-AzureADServicePrincipal -SearchString NameOfMyApp
New-AzureRoleAssignment -ObjectId $service.Id -ResourceGroupName NameOfResourceGroup -RoleDefinitionName Owner
```

After this my `service principal` got an `Owner` role and now `azure login --service-principal` works like a charm.

**Comment by devigned** [comment]
@sondreb I understand the frustration. We expect to have this feature supported in the 9/2 release of CLI.

Per the error messages, we have received feedback on those and have tried to improve them over the past few releases. When I try to login with an organizational account with MFA enabled I receive the following in CLI v0.9.6:
```
$ azure login
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Username: foo@bar.com
Password: *********
+ Authenticating...
error:   Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50079: Strong authentication enrollment (proof-up) is required.\r\nTrace ID:...}
info:    Error information has been recorded to ~/.azure/azure.err
error:   login command failed
```
This error certainly isn't the best... It won't be around much longer. Are you receiving a different error than what I have above?

Per guiding users to disable MFA, I don't believe that is the route we've espoused. When asked, we generally guide people to using service principals rather than disabling MFA. Service principals are, and will continue to be, the authentication path for non-interactive authentication flows for use in scripting and other automation scenarios. User account authentication (username / password) is intentionally interactive via MFA.

Correcting this issue is at the very top of the CLI priority list. I assure you this has our attention and is being remedied.

**Comment by devigned** [comment]
@romangromov glad to help :+1:

**Comment by MikhailTryakhov** [comment]
Hi,
but what should we do with login problems via ASM? 
I have the same 400 error trying to use ```azure login``` in ASM mode. Service principal didn't gelp too,
the error sending request is 
"D:\Projects\azure-xplat-cli>azure network vnet create testAsmVnet -l "West US"
info:    Executing command network vnet create
info:    Using default address space start IP: 10.0.0.0
info:    Using default address space cidr: 8
info:    Using default subnet start IP: 10.0.0.0
info:    Using default subnet cidr: 11
+ Looking up network configuration
error:   The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
info:    Error information has been recorded to C:\Users\Mikhail\.azure\azure.err
error:   network vnet create command failed
"

**Comment by rylev** [comment]
For reference, I was able to get around this issue by using the publish settings file - https://github.com/Azure/azure-xplat-cli#use-publish-settings-file-management-certificate-authentication

**Comment by rylev** [comment]
Just realized the above doesn't work with arm mode. Shame.

**Comment by romangromov** [comment]
FYI: 2FA now supported in ARM

**Comment by infosatheesh2020** [comment]
@romangromov Is this feature available in v0.9.9?

**Comment by yugangw-msft** [comment]
Yes, it will be available in v0.9.9

**Comment by infosatheesh2020** [comment]
Thanks :+1:

**Comment by infosatheesh2020** [comment]
@romangromov, I tried authenticating with 2FA. Below steps are followed.

[samanoha@bigboy azure-xplat-cli]$ node bin/azure login -u samanoha@mds.microsoft.com -p xxxxxxx
info:    Executing command login
\info:    Looks like you have Multi-factor authentication enabled. Try again...
\info:    To sign in, use a web browser to open the page http://aka.ms/devicelogin. Enter the code CBTTZGT52 to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameters.


Then I used code CBTTZGT52 in http://aka.ms/devicelogin, and it successfully authenticated me in phone authenticator and asked me to close the window. Even after I closed it, the CLI prompt has not exited. It is still rotating. Can you please have a look.

**Comment by yugangw-msft** [comment]
@infosatheesh2020, could you please paste the "azure.err"' content here, or send to me at yugangw at microsoft dot com. Would be great if you could set env variable of "AZURE_ADAL_LOGGING_ENABLED" to '1', run the command, and capture the verbose log as well (Just remember to remove your credential captured in the log). We can take a look before pass over to the Azure AD team.
I assume it repro's to you consistently, right?

**Comment by sharepointguy** [comment]
I have a different scenario. I want to authenticate the user via Azure AD with MFA enabled from a nonwindows system or Postman (Google App) to generate a bearer token. If MFA is disabled, I can pass form-data with parameters like client_id, resource, grant_type (value=password), username and password and get the bearer token. 

If MFA is enabled, I have to use service principal or client_id / client_secret to get me authenticated but I will not get the user details which are required for the client application to authorize (IsInRole) the user. 

Is there any other way I can generate the bearer token with MFA enabled or any other way to authenticate/authorize users?

**Comment by amarzavery** [comment]
@sharepointguy - For getting a bearer token for MFA enabled account via Azure AD, you should directly use [adal-node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs). Xplat CLI is not the tool you would want to use for getting bearer tokens. If you use the login command like this for MFA enabled account:

`azure login`

the CLI, will give you a link and access code. You should go to the link, paste the access code and then authenticate on that link. If successful, CLI will get subscriptions associated with the authenticated account.
