### ISSUE TITLE
azure login for ARM doesn't support certificates

### ISSUE THREAD

**Issue by rjmax** [Azure/azure-xplat-cli#2020]
ARM and AAD both support service principal based authentication using certificates.  However, azure login does not support using certs when logging in as a service principal - it only supports user/pass combinations.

**Comment by devigned** [comment]
ADAL supports cert auth: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/sample/certificate-credentials-sample.js

**Comment by yugangw-msft** [comment]
@devigned  It is known that ADAL has the interface. What is not certain is what to ask from the end user. The following was what I have communicated to a partner. I am pasting here in case the community has any feedback to get the design usable.

Based on the api exposed by adal, the end to end experience using azure-cli would look like
1. A users will need to provide the private key of the certificate for azure-cli to acquire a token. The key information could either be a pem file, or just a publish setting file which azure-cli can do the heavy-lifting to extract out the pem. 
2. A user needs to update the service principal’s manifest to enable the key credentials. It is a one-time thing by just following [this blog](http://blogs.msdn.com/b/exchangedev/archive/2015/01/21/building-demon-or-service-apps-with-office-365-mail-calendar-and-contacts-apis-oauth2-client-credential-flow.aspx), mainly the section of “Configuring a X.509 public cert for your application”. 

I have two related questions though
a.	There is not refresh token from the #1, which means the private key information will need to be available for the script/azure-cli to pick up automatically, because the token will expire in a hour. Azure-cli does cache some service principal information, so it can persist the keys and use that. Will users be happy with that? 
b.	What are the main reasons that users won’t like password; rather certificate? Was that for easy revocation? Or other cause?

**Comment by rjmax** [comment]
It seems that requiring a path to the pem is acceptable based on the
approaches used by others.  This way, access to the cert is handled by
filesystem ACLs rather than via providing the password.

It feels like we should ask the ADAL folks about why a refresh token isn't
provided.  As a mitigation, we can cache the path of the pem to use,
correct?

This issue at hand is removing secrets from the deployment scripts used in
CI/CD scenarios.
