### ISSUE TITLE
Azure login (0.9.10): documentation says I'll be prompted; instead, told to use interactive

### ISSUE THREAD

**Issue by squillace** [Azure/azure-xplat-cli#2186]
I think this is mostly UX: but if I specify a -u, then prompt me. Or rewrite the docs to say that if we detect an MFA requirement, we'll redirect you to the interactive login. Can we just pass the code path TO the interactive login, given that we DID just pass you a username for you to work with?

```
azure login -u rasquill@microsoft.com
info:    Executing command login
Password: **********
+ Authenticating...
error:   Interactive login is required. Use 'azure login' to interactively login.
info:    Error information has been recorded to /Users/rasquill/.azure/azure.err
error:   login command failed
```

**Comment by ahmetalpbalkan** [comment]
+1 happens to me as well. I can't login to my corp account right now. It used to wait for MFA login, it doesn't anymore.

```
$ azure login -u ah....@microsoft.com
...
verbose: Error: Interactive login is required. Use 'azure login' to interactively login.
    at __$__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login._js:125:46)
    at /usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:169:5
    at Object.__g.trampoline.flush (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:24:29)
    at ___ (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:123:61)
    at processAndReturnSubscriptions (/usr/local/lib/node_modules/azure-cli/lib/util/profile/account.js:48:21)
    at /usr/local/lib/node_modules/azure-cli/lib/util/profile/account.js:121:21
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:58:23
    at /usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/token-request.js:150:11
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/adal-node/lib/util.js:133:7)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:344:22)

error:   login command failed
```

Strangely enough I was already logged in while running this cmd. Next time I run the command without `-u`:

```
$ azure login
info:    Executing command login
-info:    To sign in, use a web browser to open the page http://aka.ms/devicelogin. Enter the code BAGHB.... to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameters.
```

Weird.

**Comment by squillace** [comment]
I'm unblocked, but the docs say that using -u will prompt you; but if your account is configured with mfa, it will NOT prompt you but instead just tell you that you used the wrong command. I'm submitting a PR with the docs, but it **should** just redirect to the mfa interactive right there, and not make the user retype something that they did correctly the first time. Basically, `azure login` is now **always interactive**, and will never prompt on the command line; while `azure login -u` is never interactive, and will only prompt if your account does not use mfa. 

I'd love this "sand-papered out" a bit....

**Comment by ahmetalpbalkan** [comment]
I was happy with just `-u` and then it prompting my password. I wonder why that's now changed to be always non-interactive.

**Comment by squillace** [comment]
that's why the issue: I expected `azure login -u <username>` and then the pwd prompt. If I needed to use MFA, **THEN** I'd get the code and the advice to redirect to aka.ms/devicelogin. But, no. Just the failure, with the frustrating advice, because if I'd known, I would have just used `azure login` in the first place....

**Comment by yugangw-msft** [comment]
@squillace @ahmetalpbalkan 
I have following notes , and hope it explains how and why it impacts the old behavior. You might know some already, but I still mention them so to get the points more logical. Let me know any comments/suggestions

1. For Msa (such as live-id) and org-id with MFA enabled (like our 'microsoft.com'), you have to login by inputting the code in the browser interactively. You have no other options, and this is not imposed by azure-cli, rather by AAD. If you still use "login -u \<user\>", this is an error case. The right one is "login" w/o any other parameters. 
2. In version 0.9.9, azure-cli had the 'auto-redirect', mainly for the reason that AAD server had the limitation that live-id login could not work well. Based on that, the decision on azure-cli was to keep the old flow (non interactive, using -u) as the main entry point.
3. But the "auto-redirect" was not that automatic, because you end up typing credentials twice. Once in the command line and the second in the browser. This is not a good practice imposed by azure-cli.
4. With full interactive flow support in 0.9.10, we expect more people will use azure-cli. The stats shows 72% people are using live id to manage azure resources. Plus, more existing org account are multi-factor enforced, so it makes sense to have the main login flow switch to interactive, and azure-cli made the command simple for that flow.
5. We are investigating whether azure-cli is able to automatically launch the browser and fill in the device code, when that becomes possible (including windows, osx, and linux), we will take another look at the 2nd point above. I will let you know.
6. The login command change, yes a breaking change, should be rather easy to remember for people, that you can either use "azure login" to start to use azure-cli or you can continue with "login -u" as an existing user. I know for people inside Microsoft, it is a breaking change, but for people outside should be rather smooth.

**Comment by amarzavery** [comment]
Closing this issue as Yugang clearly explained the reasons for design change. Please feel free to open the issue, if the need arises.

**Comment by squillace** [comment]
@yugangw-msft I appreciate the detailed explanation very much! thanks. I'd feel fine if we just say now: "we're going to MFA as the future for everyone; we've chosen to get there now and we know that it's breaking but the future will be secure." 

I'll leave this issue closed, but I'll continue submitting the PR to update the online --help switch to clarify based on the comments you've included here. At the very least, you are NOT prompted as the docs say you will be IFF you're using an account with MFA requirements, which you may or may not know offhand, depending whether you're an overworked isv. :-)
