### ISSUE TITLE
Can I access multiple azure accounts with azure-cli from same machine at same time?

### ISSUE THREAD

**Issue by buchireddy** [Azure/azure-xplat-cli#2198]
We actually have multiple azure accounts (for some valid reason) and I want to be able to run azure-cli commands for different accounts at the same time from same machine in different shells.

The problem with that is, once I login to one azure account with azure login, token will be stored in ~/.azure directory so I am not sure if I can login into another account exactly at the same time on that machine.

Is there any way to tell azure-cli not to store token in local profile so that I can use azure-cli to connect to multiple accounts at the same time from same machine?

Asked the same question on SO at: http://stackoverflow.com/q/33137145/467969

**Comment by yugangw-msft** [comment]
@buchireddy, my colleague amar has already answered your question at SO.
In short, azure-cli has no parallel protections on machine wide resources which are used to store aad access tokens and account information persistence. Even 2 concurrent login sessions use different account/username, because of the cross tenant token refreshing, it is still possible for both sessions to retrieve multiple tokens for the same tenant. This not only happens on login though, but also on any azure-cli cmdlets running at the same time which incurred automatic token refreshing on your behalf, and that still introduce racing.
It is totally feasible for azure-cli to use lock mechanism to protect them, but we just have received enough ask to get that happen.

**Comment by buchireddy** [comment]
Thanks for the reply @yugangw-msft and @amarzavery 

Do you have any plans of sticking the token in an environment variable so that all the CLI commands in that session could use the token without persisting it? Now, I'm not sure if that makes sense but that makes it easy for our use case.

I'm just starting on Azure so I'm not sure why Azure doesn't use access/secret keys like AWS but that is also another way of making this work. Thoughts?

**Comment by ramayer** [comment]
@yugangw-msft: "It is totally feasible for azure-cli to use lock mechanism to protect them, but we just have not received enough ask to get that happen."

Consider this one more request to be able to use the command-line tools on more than one Azure account at a time.

**Comment by yugangw-msft** [comment]
@buchireddy, regarding making the token as part of environment variable, this might not be very feasible, because one login session azure-cli will produce multiple token for each tenant your account is associated with, plus a pairing refresh token for every one. 
However, if you login using service principal (a pair of key and secret), then it is feasible for parallel process, because azure-cli persist no access tokens; rather just the key/secret itself.

**Comment by buchireddy** [comment]
Thanks for update @yugangw-msft 

Seems like using service principal is my best bet. I will surely try that and update you on how it goes.

Do you have any documentation or blog posts about best practices of using service principals?

**Comment by yugangw-msft** [comment]
@buchireddy check out this post: http://blog.davidebbo.com/2014/12/azure-service-principal.html, which has pretty good conceptual introduction.
It was written using Powershell commands, but equivalent cmdlets exist in azure-cli.

**Comment by amarzavery** [comment]
@buchireddy - this documentation should help https://github.com/Azure/azure-xplat-cli#non-interactive-authentication.
closing this one for now.
