### ISSUE TITLE
The specified item could not be found in the keychain

### ISSUE THREAD

**Issue by joergrech** [Azure/azure-xplat-cli#2269]
I have a similar problem to issue #2081 with azure-cli 0.9.11 on Mac OSX . I cannot execute most command and login via web or username/password does not help. I can view my subscriptions ("azure account list" does work) but not my VMs ("azure vm list" does not work). Even trying older versions, removing keychain entries or clearing account data ("azure account clear", uninstalling and removing directories) did not help. Are there any other ways to login or which version does use an older login mechanism (I upgraded from an older version but can't remember the version)?

```shell
azure vm list
info:    Executing command vm list
+ Getting virtual machines                                                     
error:   Command failed: security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

**Comment by yugangw-msft** [comment]
@joergrech there is a known issue that if your user name (given & family name) contains non-ansi character, the login command will not be able to save and retrieve the access token correctly with the error you mentioned. We will fix that in the upcoming release. If that is the case for you as well, for now, you can either chose a different user with all ansi character, or manually remove the key chain entries with kind of "azure access token". 
If it is not the case on you, could you narrow down a repro if possible?

**Comment by joergrech** [comment]
Ah ok, It might be associated with my user name on my Mac which contains an "ö" umlaut. Do you mean another user account on my Mac when you say "chose a different user with all ansi character" - or a new account on the Azure platform? However, removing the two key chain entries "azure access token" will not help (this will require a new login and after login the error reappears).

**Comment by yugangw-msft** [comment]
@joergrech, i meant the user account on the azure platform which you used in the command of "azure login". If you go to azure portal, you can take a look at the user detail through the "Directory" tab, i suspect the user name or id contains non english character.
And depend on the user type, cleaning up the entries might not help, because "login" command involves several interactions with active directory, and there is good chance the cache will be saturated with duplicates. Sorry for he confusion. Regardless, you can still create a user with all English characters, and make the user as an admin to your subscription, this will work good. In several weeks, I will push out a new drop with the right fix.

**Comment by joergrech** [comment]
Btw. can you state the last version before this faulty mechanism was introduced? I upgraded from a 0.8 or 0.7 version that worked but I did not remember the number and 0.8.12 etc is not working. Would be great if you could tell me before I have to try them all :-)

**Comment by yugangw-msft** [comment]
This bug should have there for a long time. It is a basic de-serialization bug on querying windows credential storage and mac key-chain.
I will try to sort out a bug fix this week and you can start to use dev branch.

**Comment by tboloo** [comment]
@amarzavery -> when the fix would be available? I have installed v0.9.11 and the problem is still present. I had to update my profile on live.com to remove non-ASCII characters to make azure-cli work.

**Comment by yugangw-msft** [comment]
@tboloo  we plan to release a fix through the upcoming release. The time will be at the beginning of December

**Comment by yugangw-msft** [comment]
@joergrech, @tboloo , the fix is in the dev branch, which you can get it through "npm install -g  http://github.com/Azure/azure-xplat-cli/tarball/dev".  If your current azure-cli is stuck on invalid entries, please manually remove them from the keychain; otherwise, restore you original name in your profile and good to go. Let me know if you see any issues.

**Comment by tboloo** [comment]
@yugangw-msft - fix works, thank you for your support.
