### ISSUE TITLE
azure cli is not working on OSX if user has unicode char in his giveName/familyName

### ISSUE THREAD

**Issue by DavidKarlas** [Azure/azure-xplat-cli#2349]
For example... My family name is Karlaš...(I set this in my Microsoft account)...
Result is that in OSX KeyChain it's stored as "Karla\305\241" which azure cli later doesn't like...

My workaround:
Delete Azure keys in OSX->Keychain application
Login microsoft account, change my last name to "Karlas", logout
Re-login to reflect family name change...
Use "azure login" and aka.ms/devicelogin
Works...

Error when I had Karlaš was(I replaced some values with XXXXXX for privacy...)

error:   Command failed: /usr/bin/security find-generic-password -a _authority:https\://login.microsoftonline.com/common::_clientId:XXXXXXXXXXXX::expiresIn:3599::expiresOn:2015-12-03T09\:10\:24.651Z::familyName:Karla\305\241::givenName:David::identityProvider:live.com::isMRRT:true::isUserIdDisplayable:true::resource:https\://management.core.windows.net/::tenantId:XXXXXXXXX::tokenType:Bearer::userId:XXXXXXXXX@outlook.com -s https://management.core.windows.net/ -g
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.

**Comment by yugangw-msft** [comment]
@DavidKarlas, this is the same issue with #2269
The fix is in dev branch already, which you can try out with "npm install -g http://github.com/Azure/azure-xplat-cli/tarball/dev".  Please go to "keychain access", and remove the entries with kind of "azure access token", then you should be good to do.
the installer will be available around Dev 8

**Comment by DavidKarlas** [comment]
Ok, tnx, I didn't find that issue when I opened this bug report...
