### ISSUE TITLE
[ARM/ASM] Not having --quiet impacts scripting in a bad way

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2361]
Hi folks, I started writing some bash scripts (which are set of commands executed in a particular order, often interacting with UNIX programs following the UNIX philosophy where the universal communication channel, pipes, between these programs are text streams) on top of `azure` CLI..

The immediate problem I noticed is, we print a lot of status/help messages to standard output (`stdout`). For example, in bash if I run a script such as:

    producer | consumer

what the producer prints to only stdout will get piped to consumer; stderr will not –it will just get printed to screen by the shell. This is simply because stdout is for programs and humans (to see what's going on) however stderr is purely for humans. (wanted to state this in case you might not know, which is ok)

Take `azure -h` as an example. It prints all the help/usage messages to stdout by default. Try this with other UNIX tools: run `curl -h > out`, `sed -h > out` ... You will see that none of the programs write their stuff to stdout.

That's point 1.

My argument is, our commands should provide a way for scripting (such as text or JSON, which we do). However some commands such as `azure account set <subs-id>`  will also be parts of scripts and _these commands do not have `--quiet` option`, and they print their informational messages to `stdout`.

Let's say I wrote the following program and handed to a customer:

```sh
#!/bin/bash
set -e
...
echo "[INFO] Setting azure subscription to $SUBS_ID"
azure account set $SUBS_ID --quiet
echo "[INFO] Now launching the rocket."
```

this command will print

```
[INFO] Setting azure subscription to foo
info:    Executing command account set
info:    Setting subscription to "Azure Linux Team - Dev-Test - non-ExpressRoute" with id "foo".
info:    Changes saved
info:    account set command
[INFO] Now launching the rocket.
```

This is just wrong, my `--quiet` is not honored. I need quiet because:

1. I don't want to see azure messages in my program
2. My customer does not care about the program.
3. If azure command fails, of course me and my customer should know why the program has failed.

In case of an error, azure CLI already prints output to /dev/stderr, which is great. However this is implicit and we're treating stdout as something we can redirect to /dev/null to make it --quiet.

Instead we should have `-q/--quiet` and print NOTHING to stdout if `azure account set` command succeeds, and print stuff to stderr when it fails (but you still print nothing to stdout).

Same with `azure vm create`. It should not print anything at all to the screen if I say `--quiet`. Some commands that gather information (such as `vm list`) of course have their `--json` argument for scripting in bash, that is already great. But we should utilize `--quiet` instead of telling people to `1>/dev/null`.

**Comment by yugangw-msft** [comment]
I have following comments on this issue before come out with my suggestion
1. Based on the philosopher of [silence is golden](http://www.linfo.org/rule_of_silence.html), for most azure-cli cmdlets, running on unix should output nothing unless error. I agree "account set" should not output that much as we have.
2. Azure-cli is written to run on unix, but also on windows, which is more verbose by default and not that consistent like unix.
3. Most azure-cli comdlets take much longer time than OS native commands. For any commands longer than couple of seconds, there is also a rule that you should show progress text; or people will start to wonder the cmdlets are hanging.
4. For lots of cmdlets "--quiet" or "-Q" are already interpreted as to just suppress prompts, say before delete an azure group. It doesn't apply on the progress text. Because of the previous point of long running, it is reasonable.
5. For "-h", I tried a few commands just now on ubuntu 14.04, the "sed -h" goes to stderr, but the "curl -h" and "ls --help" both go to stdout. So on this part, unix are not consistent by itself. I much prefer to get it to stdout , because not only "ls" (the very first command everyone uses) does it, also by common sense stderr is reserved for real error text, right?

Because of those, I thought a little, at this stage, the best i can come out with is probably to have a common flag such as "--silence". With that azure-cli will not dump anything to stdout (including json output). The stderr will still get proceeded. Doing that will conform to the rule of the silence.
Thoughts?

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft --silent is totally alright. I don't think there's any point of “silent by default” as most of our operations (at least the ones I use) take at least ~1 minute and I appreciate progress output in interactive mode, it's just when I'm scripting I find myself doing `1>/dev/null` all the time. :-)

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, based on old comments there is an terminology of "terse" used already in azure-cli, but never wired up. I made it work and in future you just use "--terse". Sounds good?

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft I'm programming since I was 9, first time I'm hearing the "terse" word (but then English is my second language). My opinion is, word choice is not correct, I'd suggest validating this with someone else's opinion. I don't need this argument, I just want to inspire the next versions of CLI to have the right concept implement.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, thanks for the input. First time i came across the "terse" as well. 
@devigned, @amarzavery, not critical, but chip in your comment. This falls into the language domain and English is not my main language . 
My opinion on "silent" was I felt it rather close in the meaning to the "quiet" flag which has been used across cli command already. But just now i looked up the dictionary, and saw it means "no sound" vs "not very loud"  for "quiet". So the meaning difference is not that subtle though.

**Comment by ahmetalpbalkan** [comment]
if we ever write a new CLI, `--quiet` probably should not mean `--yes`/`-y` so that we can use `--quiet`/`-q` for silencing the output. :)

**Comment by yugangw-msft** [comment]
Based on the conversation, i am removing the "--terse" flag from the PR of "logging improvement" due to less values. The current discussion is about cli's future.

**Comment by devigned** [comment]
Informational messages and diagnostics should go to stderr. They should not be on stdout.

--quiet / -q is the way to go.

**Comment by mayurid** [comment]
@eduardkoller : Can you add to backlog and let us know the proposal

**Comment by ahmetalpbalkan** [comment]
Fundamentally our xplat-cli is just too chatty and has animations and stuff for a good reason (b/c we mostly assume humans are interacting with it; not headless scripts). So --quiet probably will never happen on this version at least. `1>/dev/null` to rescue.
