### ISSUE TITLE
[arm] certain actions don't work under Fiddler or mitmproxy

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2390]
I noticed that very basic requests will work in Fiddler and mitmproxy. Unfortunately, more complicated requests do not.

Steps:

1. Open Fiddler.
2. Enable HTTPS interception, ignore cert errors.
3. Start capturing.
4. Open Command Prompt
5. azure login
6. set https_proxy=http://localhost:8888 (or whatever port you're running Fiddler on)
7. set HTTPS_PROXY=http://localhost:8888 (paranoia about this env var name)
8. azure group create -n "SomeRandomCoolName" -l "westus"

It will successfully "Getting resource group SomeRandomCoolName", but then fail on "Creating resource group SomeRandomCoolName".

The error is "tunneling socket could not be established, statusCode=408".

Notice in Fiddler:

1. a 404 since the resource group doesn't exist (expected)
2. a 408 because the client didn't send data

When using mitmproxy on linux, the second request simply isn't shown at all.

For what it's worth, I've mostly noticed this occuring on non-GET requests - specifically POSTs at least.

**Comment by colemickens** [comment]
Another bit of information, in this case, it looks like the SSL connection was kept open, but the client sent CONNECT again, even though it shouldn't have.

Also, let me know and I can provide repro directions for linux+mitmproxy if that's helpful at all.

**Comment by devigned** [comment]
Hi Cole,

Does it work if you do the following (via https://github.com/Azure/azure-xplat-cli#use-web-debugging-proxy):
```bash
set NODE_TLS_REJECT_UNAUTHORIZED=0
or
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

Also, on linux are you using set or export?

**Comment by devigned** [comment]
Also, take a look at this thread: https://github.com/npm/npm/issues/2472

**Comment by colemickens** [comment]
On Linux I'm using export.

On Windows, I just did `set NODE_TLS_REJECT_UNAUTHORIZED=0` and I'm seeing a failure. Though, it's now "tunneling socket could not be established, cause=Parse Error" (different cause).

**Comment by devigned** [comment]
> On Linux I'm using export.

Sorry... Just making sure the computer's plugged in.

**Comment by devigned** [comment]
Could this be part of the issue? https://github.com/npm/npm/issues/3084

**Comment by colemickens** [comment]
Hm, no luck so far.

On Linux, per those two npm issues, I tried:
1. `npm config set registry http://registry.npmjs.org`
2. `npm config set strict-ssl false`
3. translated localhost->127.0.0.1
4. `export NODE_TLS_REJECT_UNAUTHORIZED=0`

I also tried setting "proxy" and "https-proxy" via `npm config set` but those had zero effect on the actual traffic.

I'm not sure how to do the first and second one in Windows since I installed from MSI and don't have NPM installed manually. (Additionally, I don't hold much hope in them. The SSL is good enough for the GET requests and the registry was for the user with registry-specific issues).

Does this repro for you? If not, did you install from MSI? I can't think of anything weird I've done to my Windows box.

**Comment by yugangw-msft** [comment]
@colemickens, i took a look at the fiddler case. This issue should repro on all requests with a non empty body. The error story plays out like following. 
1. sdk library will always put in the header of "content-length", before hands over to [request package](https://github.com/request/request)
2. the "request" package see the HTTP_PROXY is set, it will first create a http tunnel by sending out the "connect" request. Its headers derive from the sdk's request, so it contains the "content-length" field; however, this is invalid because it has no body, and hence it gets rejected by azure.

By reading the source code of the request package, clearly, azure sdk should not set the "content-length", because the request package will always set the field, and it does it after initializing the tunnel, so tunnel's "connect" is always right.

@amarzavery, let us update the code-gen and not to add the 'content-lenght", unless we do have specific reasons. So far it is redundant and interferes with the proxy scenarios. Also, clearly, we do not need the proxy filter, and the request package is doing that already, likely does better than us

@colemickens, could you let me know the steps of setting up the mitmproxy?  I am not familiar with it, but i can verify whether there are other issues after get on the same pages with you.

**Comment by colemickens** [comment]
@yugangw-msft The steps for running Fiddler are:

1. Install `mitmproxy` using your distro conventions.
2. Run `mitmproxy` once and then close.
3. There is a public CA certificate in your `~/.mitmproxy` directory. Use distro conventions to install this new root certificate authority. Keep the private key safe. Ubuntu root CA install instructions are here: http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate/94861#94861

Thanks for tracking this down. I'd be more than happy to take a look once there's a fix in a branch or a PR.

I don't remember the exact scenario, but as you noted, anything with a post body was triggering it.

**Comment by yugangw-msft** [comment]
@colemickens, thanks.
The root fix will be at [autorest](https://github.com/Azure/autorest/blob/master/AutoRest/Generators/NodeJS/NodeJS/Templates/MethodTemplate.cshtml#L139) as sdk libraries are generated. @amarzavery will find time to remove the lines, and produce new library code without setting the "content-length"; rather let "request" package do it. Once that is done, azure-cli's package json will be updated to use newer version. then all should work.

**Comment by BrendanThompson** [comment]
Having this same issue when trying to use CNTLM. As the `azure-cli` doesn't support authenticated proxies. Anything with a `GET` works, it just falls over when it's a `POST` or `PUT`

**Comment by yugangw-msft** [comment]
We have regenerated and published node sdk library with the change i mentioned. #2492 picked up those libraries. I tried out the latest dev branch, fiddler now is able to capture delete, put, etc w/o problems. 2 notes:
1. Old cmdlets, those asm ones, were no updated, because related libraries are not actively maintained through code generators. If you use those commands, the proxy will not work,  If it becomes blocking issue for you, let us know.
2. @colemickens, I have not tried mitmproxy, because i only have a azure VM which I use SSH to connect. I assume i will need a desktop shell to check out the proxy? Let me know otherwise. Anyway I will use other proxy software on mac to double check.

**Comment by colemickens** [comment]
@yugangw-msft mitmproxy is ncurses based so you can do it remotely in a terminal, that's what I'm doing.

Is this in a released version? It will be easier for me to try it that way.

**Comment by yugangw-msft** [comment]
@colemickens, it is not in released branch. You can either wait, or try out now using tarball endpoint.
    npm install -g https://github.com/Azure/azure-xplat-cli/tarball/dev
Since it is pulling from not pre-compiled source, suggest delete "~/.streamline" before use to avoid [flakiness](https://github.com/Sage/streamlinejs/issues/290).

**Comment by colemickens** [comment]
@yugangw-msft Great! I can confirm that the PUT request demonstrated in the original issue is now able to complete and is visible in `mitmproxy`.

I'll leave it up to you how to handle closing this. I don't know if you want someone to confirm with Fiddler or wait until this is available in a release. I don't have a Windows machine with me today to test.

**Comment by BrendanThompson** [comment]
Can confirm that this is now working through `cntlm` as well as straight through the normal proxy! What release time frame are we looking at?

**Comment by yugangw-msft** [comment]
@colemickens , @BrendanThompson , I verified with fiddler in window.
The change came couple of days short, so it will be in 0.9.16 at the beginning of next month.
