### ISSUE TITLE
azure network nic inbound-nat-rule add flag changed in 0.9.14, but not documented anywhere

### ISSUE THREAD

**Issue by shahidhk** [Azure/azure-xplat-cli#2430]
For `azure network nic inbound-nat-rule add` command, the `--inbound-nat-rule-name` in `v0.9.13` has been changed to `--lb-inbound-nat-rule-name` in `v0.9.14`, but it is not documented anywhere (not in changelog also). 

How come a breaking change happen in a patch release (assuming semver is followed) and it is not documented?

**Comment by yugangw-msft** [comment]
@shahidhk azure-cli is still in pre-release. I have reflected this in the release tab; otherwise, this should have caused major version change, which we are not doing.
@romangromov, please confirm whether this is expected. Next time, I will pay attention to call out the cmdlet interface change in the changelog.
@amarzavery for FYI.

**Comment by shahidhk** [comment]
@yugangw-msft Thanks for the update. I understand that azure-cli is still in pre-release. But, could not find this in changelog for the release.

**Comment by romangromov** [comment]
@yugangw-msft that is true, `--inbound-nat-rule-name` changed to `--lb-inbound-nat-rule-name` to follow the same style with other parameters naming convention. In future cases, will declare braking changes in PR description so you can update change log quickly

**Comment by yugangw-msft** [comment]
closing. no code change is needed; other than we need to do better moving forward
