### ISSUE TITLE
"Unsupported wstrust endpoint version" error after login -u on Mac CLI version 0.9.14

### ISSUE THREAD

**Issue by dlepow** [Azure/azure-xplat-cli#2497]
Two customers report issue when attempting to log into Mac CLI using "login -u <username">. See Disqus comments and error stack trace at https://azure.microsoft.com/en-us/documentation/articles/xplat-cli-install/.

**Comment by amarzavery** [comment]
Is the account a valid org id for which 2FA is disabled? Can they try interactive login ?

**Comment by dlepow** [comment]
I will ask.

**Comment by amarzavery** [comment]
This issue was reported by Somahant
I am using azure version 0.9.14 and still see the issue.  I am not able to login via CLI.  I need this functionalitiy to automate how we start the resources via ARM on demand.
/usr/local/bin/azure login -vv -u smohanat@akamai.com
info:    Executing command login
Password: ***********
verbose: Authenticating...
error:   Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.
silly:   {
silly:       stack: 'Error: Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.\n  <<< async stack >>>\n  at __1 (/usr/local/azure/lib/commands/login.js:100:28)\n  <<< raw stack >>>\n    at Logger.createError (/usr/local/azure/node_modules/adal-node/lib/log.js:201:13)\n    at WSTrustRequest.acquireToken (/usr/local/azure/node_modules/adal-node/lib/wstrust-request.js:203:25)\n    at TokenRequest._performWSTrustExchange (/usr/local/azure/node_modules/adal-node/lib/token-request.js:286:11)\n    at TokenRequest._performUsernamePasswordForAccessTokenExchange (/usr/local/azure/node_modules/adal-node/lib/token-request.js:311:8)\n    at /usr/local/azure/node_modules/adal-node/lib/token-request.js:371:12\n    at Request._callback (/usr/local/azure/node_modules/adal-node/lib/util.js:119:7)\n    at self.callback (/usr/local/azure/node_modules/request/request.js:344:22)\n    at Request.emit (events.js:107:17)\n    at Request.onRequestError (/usr/local/azure/node_modules/request/request.js:961:8)\n    at ClientRequest.emit (events.js:107:17)',
silly:       message: 'Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.',
silly:       __frame: {
silly:           name: '__1',
silly:           line: 47,
silly:           file: '/usr/local/azure/lib/commands/login.js',
silly:           prev: undefined,
silly:           calls: 1,
silly:           active: false,
silly:           offset: 53,
silly:           col: 27
silly:       },
silly:       rawStack: 'Error: Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.\n    at Logger.createError (/usr/local/azure/node_modules/adal-node/lib/log.js:201:13)\n    at WSTrustRequest.acquireToken (/usr/local/azure/node_modules/adal-node/lib/wstrust-request.js:203:25)\n    at TokenRequest._performWSTrustExchange (/usr/local/azure/node_modules/adal-node/lib/token-request.js:286:11)\n    at TokenRequest._performUsernamePasswordForAccessTokenExchange (/usr/local/azure/node_modules/adal-node/lib/token-request.js:311:8)\n    at /usr/local/azure/node_modules/adal-node/lib/token-request.js:371:12\n    at Request._callback (/usr/local/azure/node_modules/adal-node/lib/util.js:119:7)\n    at self.callback (/usr/local/azure/node_modules/request/request.js:344:22)\n    at Request.emit (events.js:107:17)\n    at Request.onRequestError (/usr/local/azure/node_modules/request/request.js:961:8)\n    at ClientRequest.emit (events.js:107:17)'
silly:   }
info:    Error information has been recorded to /Users/smohanat/.azure/azure.err
verbose: Error: Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.
  <<< async stack >>>
  at __1 (/usr/local/azure/lib/commands/login.js:100:28)
  <<< raw stack >>>
    at Logger.createError (/usr/local/azure/node_modules/adal-node/lib/log.js:201:13)
    at WSTrustRequest.acquireToken (/usr/local/azure/node_modules/adal-node/lib/wstrust-request.js:203:25)
    at TokenRequest._performWSTrustExchange (/usr/local/azure/node_modules/adal-node/lib/token-request.js:286:11)
    at TokenRequest._performUsernamePasswordForAccessTokenExchange (/usr/local/azure/node_modules/adal-node/lib/token-request.js:311:8)
    at /usr/local/azure/node_modules/adal-node/lib/token-request.js:371:12
    at Request._callback (/usr/local/azure/node_modules/adal-node/lib/util.js:119:7)
    at self.callback (/usr/local/azure/node_modules/request/request.js:344:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/usr/local/azure/node_modules/request/request.js:961:8)
    at ClientRequest.emit (events.js:107:17)
error:   login command failed

**Comment by amarzavery** [comment]
This issue was reported by Craig Silva
Just wanted to add that my experience is the same as the above with cli v 0.9.14.

I'm trying to work out the logic of providing a docker install that fails before doing anything i.e. no gui web client.

Is there a work around?

**Comment by amarzavery** [comment]
closing this as there there is no traction from adal-node
