### ISSUE TITLE
azure vm image list isn't working

### ISSUE THREAD

**Issue by EslamElHusseiny** [Azure/azure-xplat-cli#2533]
I've tried the following : `azure vm image list westus canonical ubuntuserver` as per documentation here https://azure.microsoft.com/en-gb/documentation/articles/resource-groups-vm-searching/

and the output of the command is  

`info:    Executing command vm image list`
`error:   msRest.addSerializationMixin is not a function`
`info:    Error information has been recorded to /Users/user.name/.azure/azure.err`
`error:   vm image list command failed`

I'm using azure-cli version 0.9.15

**Comment by amarzavery** [comment]
That is definitely a bug and will be fixed in the upcoming release.

Thanks,
Amar Zavery

On Feb 14, 2016, at 4:22 PM, "Eslam" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tried the following : azure vm image list westus canonical ubuntuserver as per documentation here https://azure.microsoft.com/en-gb/documentation/articles/resource-groups-vm-searching/<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fazure.microsoft.com%2fen-gb%2fdocumentation%2farticles%2fresource-groups-vm-searching%2f&data=01%7c01%7camzavery%40microsoft.com%7c7f7ee353dfd34ef4e30e08d3359e153b%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=1hnDUvswSQ%2fjcFUMl%2fzk6UiBRMQDiyA7ZIdJ6aVIEBU%3d>

and the output of the command is

info: Executing command vm image list
error: msRest.addSerializationMixin is not a function
info: Error information has been recorded to /Users/user.name/.azure/azure.err
error: vm image list command failed

I'm using azure-cli version 0.9.15

-

**Comment by amarzavery** [comment]
@EslamElHusseiny - It seems your installation is corrupted. How did you install 0.9.15 on your machine? Was it via npm ?
If so, then please uninstall `npm uninstall -g azure-cli`
clear the global cache `npm cache clear -g`
Make sure to delete the `/Users/$username/.azure/.streamline` directory..
Now, install again `npm install -g azure-cli`. 

I tried this on my box and it seemed to be working fine.
```cmd
D:\sdk>azure vm image list westus canonical ubuntuserver
info:    Executing command vm image list
+ Getting virtual machine image skus (Publisher:"canonical" Offer:"ubuntuserver" Location:"westus")
data:    Publisher  Offer         Sku                OS         Version          Location  Urn                                      
data:    ---------  ------------  -----------------  ---------  ---------------  --------  --------------------------------------------------------
data:    canonical  ubuntuserver  12.04.3-LTS        undefined  12.04.201401270  westus    canonical:ubuntuserver:12.04.3-LTS:12.04.201401270
data:    canonical  ubuntuserver  12.04.3-LTS        undefined  12.04.201401300  westus    canonical:ubuntuserver:12.04.3-LTS:12.04.201401300
data:    canonical  ubuntuserver  12.04.4-LTS        undefined  12.04.201402270  westus    canonical:ubuntuserver:12.04.4-LTS:12.04.201402270
data:    canonical  ubuntuserver  12.04.4-LTS        undefined  12.04.201404080  westus    canonical:ubuntuserver:12.04.4-LTS:12.04.201404080
data:    canonical  ubuntuserver  12.04.4-LTS        undefined  12.04.201404280  westus    canonical:ubuntuserver:12.04.4-LTS:12.04.201404280
````

**Comment by huangpf** [comment]
It seems it's AutoRest client related only.

**Comment by amarzavery** [comment]
@huangpf - Yes the error was seen because of AutoRest generated client. However, there is nothing wrong in the generated client. As far as I can say, porting cmdlets to consume AutoRest generated client was done correctly. Our [tests](https://github.com/Azure/azure-xplat-cli/blob/dev/test/commands/arm/vm/arm.vm-image-list-tests.js#L96) passed as well. It works well on my local box as well. This is most certainly an issue with the corrupt installation.

**Comment by EslamElHusseiny** [comment]
brew installs 0.9.13
brew cask installs 0.9.14
then I've installed the latest "0.9.15" from the binary provided in this link http://go.microsoft.com/fwlink/?LinkId=252249

**Comment by EslamElHusseiny** [comment]
I've removed all the installed versions of azure and re-installed the binary version and it works fine now, 
Thanks
