### ISSUE TITLE
azure storage blob list  hangs when listing large container

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-xplat-cli#2658]
CLI Version: 0.9.18
OS Type: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
Linux ukc-bk04 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Installation via:  npm 

Description:
`azure storage blob list` hangs when listling large container

Steps to reproduce:
1) Make a container with a large number of blobs within a "folder" style hierarchy ( a few hundred blobs  will normally be sufficient )
2) Run `azure storage blob list --json`
3) Notice how it lists a handful of blobs and then hangs and never completes.

**Comment by amarzavery** [comment]
@hasonmsft @yaxia - Can you take a look at this ?

**Comment by hasonmsft** [comment]
@udf2457 , thanks for raising this issue. Could you try `azure storage blob list` without the `--json` switch or redirect the output to a local file? As you said that 'it lists a handful of blobs', the service API call should be finished. Looks like the output text is too long and exceed the console output buffer size limitation. Then you can only see part of them. And the command already completed. 

  {
    "name": "folder1/testlargecontainer61",
    "properties": {
      "last-modified": "Mon, 21 Mar 2016 01:49:36 GMT",
      "etag": "0x8D3512B0F200562", **(end of the output)   (console indicator)  xxx@xxx:~$**

@amarzavery , from my side, when we use the "--json" switch and the output is too long which exceed the console output buffer limitation, we can only see the beginning part of the output, instead of the tail part of the output. Is this expected?

**Comment by yaxia** [comment]
@amarzavery Could you please close it as it looks like a console buffer issue? @udf2457 do you agree with our conclusion? Thanks
