### ISSUE TITLE
npm Upgrade path broken

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2678]
CLI Version: **0.9.14**
OS Type: Mac
Installation via:  npm

I had 0.9.14 on my home Mac today and I ran `npm upgrade -g azure-cli`. It exited silently and with exitcode=0. When I ran `azure --version` I saw it's still 0.9.14. Then I realized how crappy piece of software `npm` probably is and I was right:

    npm uninstall -g azure-cli; npm install -g azure-cli; azure --version
    0.9.18

This is not the first time it's happening to me, I was able to repro it on a separate Mac and I'm certainly not alone (cc: @squillace  is having the same issue).

**Comment by squillace** [comment]
repro. silent fail on upgrade from 0.9.16 to .18.

**Comment by mayurid** [comment]
@ahmetalpbalkan, @squillace  : Was the first install that you had (of 0.9.14) using MAC installer or npm

**Comment by ahmetalpbalkan** [comment]
@mayurid I always used npm

**Comment by ahmetalpbalkan** [comment]
there u go another repro:


```
$ azure -v; sudo npm upgrade -g azure-cli; echo ExitCode=$?; azure -v
0.9.19
ExitCode=0
0.9.19
```

**Comment by haocs** [comment]
@ahmetalpbalkan @squillace could you try npm upgrade in verbose? 
``` $ sudo npm upgrade -g azure-cli -dd```
and check if you can see the following log message in the output
```
outdated not updating azure-cli because it's currently at the maximum version that matches its specified semver range
```

If yes, it is an issue of(design decision made by) NPM. According to their docs if you do 'npm update -g', it will take **wanted**(which equals to current) version instead of the latest one.

> wanted is the maximum version of the package that satisfies the semver range specified in package.json. If there's no available semver range (i.e. you're running npm outdated --global, or the package isn't included in package.json), then wanted shows the currently-installed version.

Here is the doc about NPM outdate stratigies. https://docs.npmjs.com/cli/outdated
and there are some discussions of this: https://github.com/npm/npm/issues/9690 https://github.com/npm/npm/issues/10590
To update to the latest version:
```bash
sudo npm install azure-cli@latest -g
```

If you observed a different issue, could you attach more log to help us figure out the issue?

**Comment by ahmetalpbalkan** [comment]
@haocs I believe I have used `npm upgrade` to this day and that's what's broken.

When I use `npm install` it works, but I think you should make `npm upgrade` work again (it worked until 0.9.16 or so) because that's what got broken.

**Comment by ahmetalpbalkan** [comment]
@haocs here's the `npm upgrade` output

```
$ sudo npm upgrade -g azure-cli -dd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/5.10.1/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'upgrade',
npm verb cli   '-g',
npm verb cli   'azure-cli',
npm verb cli   '-dd' ]
npm info using npm@3.8.3
npm info using node@v5.10.1
npm verb get https://registry.npmjs.org/azure-cli not expired, no request
npm verb outdated not updating azure-cli because it's currently at the maximum version that matches its specified semver range
npm verb exit [ 0, true ]
npm info ok
```
