### ISSUE TITLE
Unable to find user with upn <email address>

### ISSUE THREAD

**Issue by silhouettes** [Azure/azure-xplat-cli#2709]
CLI Version: **0.9.19**
OS Type: Win
Installation via:  npm

Mode: **ARM**

Description:
Unable to find user with upn \<email address\>

Steps to reproduce:
1) Run `azure keyvault create --vault-name 'TestVault' --resource-group 'KeyVaultTest' --location 'westus'`

Error stack trace:

```
2016-04-02T00:34:16.408Z:
{ [Error: Unable to find user with upn rich@rkhua.com]
  stack: [Getter/Setter],
  __frame: 
   { name: 'getAccountFromSubscription',
     line: 889,
     file: 'C:\\Users\\rihua\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\keyvault\\keyvault.js',
     prev: 
      { name: 'getObjectId',
        line: 839,
        file: 'C:\\Users\\rihua\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\keyvault\\keyvault.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 9,
        col: 16 },
     calls: 1,
     active: false,
     offset: 12,
     col: 15 },
  rawStack: [Getter] }
Error: Unable to find user with upn rich@rkhua.com
  <<< async stack >>>
  at getAccountFromSubscription (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\keyvault\keyvault.js:901:16)
  at getObjectId (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\keyvault\keyvault.js:848:17)
  at __2 (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\keyvault\keyvault.js:175:22)
  <<< raw stack >>>
    at ___ (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\keyvault\keyvault.js:881:20)
    at ___ (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-graph\lib\operations\userOperations.js:462:12
    at retryCallback (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:535:7
    at handleRedirect (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:512:9)
    at C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\lib\util\logging.js:412:7
    at Request._callback (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\node_modules\ms-rest-azure\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Users\rihua\AppData\Roaming\npm\node_modules\azure-cli\node_modules\request\request.js:199:22)
```

**Comment by amarzavery** [comment]
@msfcolombo - Can you take a look at this issue?

**Comment by msfcolombo** [comment]
@silhouettes The `keyvault create` command adds the current user as an administrator of the vault you are creating.

The error you are getting often means the user is not a member in the active directory of current tenant. You can find the current tenant with the command `azure account list` to find the active subscription, then `azure account show <id>` on the active subscription. That will show the current tenant.

If you are at the wrong subscription or tenant, you must call `azure account set <id>` to switch to the correct one, or use the `--tenant` argument of the `azure login` command.

If you are in the correct account, then you must add yourself to the active directory or ask your administrator to do so.

If you don't want to be administrator of the key vault you are creating, you must login as a service principal or another user. In order to login as a service principal, use the `--service-principal` flag of the `azure login` command.

**Comment by daviderickson** [comment]
@amarzavery @msfcolombo 
I have the same problem, as above.  I have checked, and my user exists in the default AD directory, since my account is the main account for azure.  I have also separately tried the alternate suggestion logging in as a service principal for an application in the same default directory, and get a different error:

info:    Executing command keyvault create
+ Checking pre-condition
warn:    No object ID is selected. The current user's object ID will be used by default
error:   {"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"Access denied to the specified API version."}}}

The service principal is set as an owner on the resource group that the keyvault is trying to be created in.

**Comment by amarzavery** [comment]
#2742 - Duplicate

**Comment by amarzavery** [comment]
@msfcolombo - More customers are facing this issue. Key Vault is one of the teir1 RPs. Please try to resolve this at the earliest.

**Comment by msfcolombo** [comment]
@amarzavery We are looking at this. A possible breaking change to improve reliability is to create a vault without any administrator. This means the user would have to explicitly add someone or some application as admin before managing keys and secrets. Regarding @daviderickson comment citing "Access denied to the specified API version", it looks like a breaking change on Graph REST service. We are calling Graph through the provided CLI infrastructure. Will keep you updated.

**Comment by lionello** [comment]
If someone else finds this, I solved this by explicitly adding the newly created user to the "Administrators" for the relevant subscription.
