### ISSUE TITLE
vm create with boot diagnostics enabled

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2763]
CLI Version: **0.9.19**
Mode: ARM

`azure vm create` should have an argument to have VM Boot Diagnostics enabled upon creation. Otherwise we are asking users to go to portal and enable it once the VM is created. It is not particularly the best experience.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan this option is exposed (well, it is the opposite for disable) and by default it is to enable it. Check out the code [here](https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/vm/vm._js#L104). I have created one just now, and it is enabled. Please double check, or let me know if i missed some.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft I probably assumed it is not there and opened up an issue. This is great thanks.

**Comment by boredom2** [comment]
For me, this option is not working. I add --boot-diagnostics-storage-uri to the corresponding Storage Account. The VM is created without problems, but (according to the Portal), without Diagnostics enabled.
When I try to enable it later with azure vm enable-diag -a STORAGE-ACCOUNT, it fails (because the Storage account is under a different Ressource Group). Without the "-a", it works (but I dont know, where its stored?)
