### ISSUE TITLE
MKDIR fails in Azure CLI, Windows 7 Enterprise

### ISSUE THREAD

**Issue by ltenison** [Azure/azure-xplat-cli#2898]
CLI Version: Latest
OS Type: Win 7 Enterprise
Installation via:  npm /  win-or-mac installer 

Please refer to this closed issue:
Running any command result in an error #1530

It is still happening on Windows 7 Enterprise.  See attached.
![captureazclibug](https://cloud.githubusercontent.com/assets/9934492/15521552/4bad7c56-21c1-11e6-88c4-0a13ccae188e.JPG)

**Comment by amarzavery** [comment]
@ltenison - We do not recommend powershell prompt for running the cli commands. Can you please try cmd prompt or git bash and let us know if that is an issue?

**Comment by ltenison** [comment]
Amar,

You are partially correct.  On my Win 7 Enterprise laptop, the cmd.exe DOS prompt fails with the same error I saw in PowerShell.  But the GitHub “shell” works – the “azure” cmd with no parameters brings up the CLI without error.

Thanks for responding so quickly.  I also tested the CLI installation from my personal Windows 10 desktop computer and it worked fine, even from PowerShell.  The instructor in a Pluralsight class I’m taking (Tim Warner) uses Win 8.1 and it works for him.  Therefore, I suspect this problem is unique to the Win 7 Enterprise platform and perhaps to our corporate image of Win 7.

Regards,
Larry Tenison


[cid:image001.png@01D1B5DB.DDBF92C0]
Larry Tenison  |  Sr. Consultant  |  Insight
t. 480.366.7380 |  c. 503.789.6402  |  larry.tenison@insight.com<mailto:larry.tenison@insight.com>  |  insight.com<http://www.insight.com>

**Comment by kyhoop** [comment]
The reason for this issue is that when you are on a domain joined machine with roaming/redirected folders and you launch PowerShell in Administrator mode it defaults to C:\Windows\System32.

To test, launch it without Administrator mode and run the same command.  You will notice your path is likely your U:\ drive.

A quick fix is to just map U:\ once you launch powershell in administrator mode using (net use U: "YOURPATH")

If you don't know your path, just check to what that path maps to in Windows Explorer.  It is probably a \\somefilesharelocation\home$
