### ISSUE TITLE
List instance-ids for VMs under VMSS and ACS

### ISSUE THREAD

**Issue by jadbox** [Azure/azure-xplat-cli#3046]
CLI Version: 0.10.2
OS Type: Ubuntu: Linux 4.6.4
npm: 3.10.3
node: v6.3.1

Description:
The CLI provides ways to specifically `deallocate` or delete instances from the vmss, provided that an `instance-id` is given. However, there doesn't seem to be a cli command to fetch all instance-ids under the vmss (or acs).

Expected:
At least for VMSS, there should be a command to list instance-id(s). It would also be create if ACS also support this (although it does not have deallocate/delete commands yet).

**Comment by jadbox** [comment]
Also, is there a way to get the IP address behind the instance-id?

**Comment by huangpf** [comment]
@jadbox I think it's by design that we don't have to provide a separate command, because the instance IDs can be determined by the capacity: 0, 1, ..., N-1, where N is the capacity number. Did you find any case that is against this assumption?

If so, please help attach the logs and reopen the issue. Close for now. Thanks.

**Comment by huangpf** [comment]
Also, the following commands will show the actual instance IDs for each VM: ```azure vmssvm list <rgname> <vmssname>```.
