### ISSUE TITLE
ad app create: Creating application undefined

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#3053]
CLI Version: **0.10.2**
OS Type: Mac
Installation via:  npm
Mode: **ARM**

see `Creating application undefined`

```
$ azure ad app create --name foo --identifier-uris http://localhost/$RANDOM$RANDOM --home-page http://localhost --password "$pwd"
info:    Executing command ad app create
+ Creating application undefined
data:    AppId:                   bf3ad7d8-x-x-x-x
data:    ObjectId:                71c2bd02-x-x-x-x
data:    DisplayName:             foo
data:    IdentifierUris:          0=http://localhost/x
data:    ReplyUrls:
data:    AvailableToOtherTenants: False
data:    HomePage:                http://localhost
info:    ad app create command OK
```

**Comment by amarzavery** [comment]
Thanks for pointing this. It will be fixed in the upcoming release.

BTW, we have simplified the process of creating an SP. The user need not know about creating an application. `azure ad sp create` will create an application for the user behind the scene.

CRUD on an SP: `azure ad sp create| set | show | list| delete`
Take a look at this [doc](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md).

**Comment by ahmetalpbalkan** [comment]
@amarzavery thanks for letting me know!
