### ISSUE TITLE
Azure Login when Logged In Should be No-Op

### ISSUE THREAD

**Issue by apeschel** [Azure/azure-xplat-cli#3098]
CLI Version: **0.10.3 (node: 5.12.0)**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure login` should be a no-op if you are already logged in.

There is no reason to go through the full login process if azure-cli is already logged in. `azure login` should check if the user is logged in and perform a no-op if they are.

Steps to reproduce:
1) Run `azure login`
2) Authenticate
3) Run `azure login` again
4) Pointlessly re-authenticate
5) Have fun repeating ad-infinitum

**Comment by amarzavery** [comment]
There are various reasons to not make this a no-op.
1. It could be possible that your tokens are expired.
2. When the user executes `azure login`, an interactive session happens, where the user will be given a link and the code. The user pastes the code in the portal and authenticates over there. After the auth is successful, the CLI gets the token from ADAL. There is no way for CLI to know upfront which userid, is the user going to use in this case.

It is better to keep it simple, rather than making it a no-op by trying to be smart and goofing up. 

The user can execute any command and if login is required the CLI will throw an informative error and tell the user to do so.

**Comment by apeschel** [comment]
@amarzavery Those are valid points, thanks for the feedback
