### ISSUE TITLE
azure login --certificate-file initiates device auth

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#3252]
CLI Version: **0.10.5**
OS Type: Mac
Installation via:  npm
Mode: asm

Environment: **US Government**

```
c:\Users\ahmetb\Desktop> azure login --environment AzureUSGovernment --certificate-file FF.pem
info:    Executing command login
- Authenticating...info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code BDM6XXXXX to authenticate.
```

Is this normal? I am expecting it to just login with the cert.

**Comment by eduardkoller** [comment]
@yugang-msft - is this the desired behavior?

**Comment by colemickens** [comment]
Did you figure this out Ahmet? I'm currently blocked on this. Can we **please** provide a single example of cert auth *anywhere*. Whether it's here, on the docs site, on a random MSDN blog, in a Tweet... something?

**Comment by colemickens** [comment]
```shell
azure login \
    --certificate-file "/home/cole/publishing_management_certificates/RhelPublishingFairfax.pfx" \
    --thumbprint "8FA6F602FC101989BA3E8038E3177EE6C7904616" \
    --environment "AzureUSGovernment"
```

This initiates device auth as well... Also, I have no idea why I should need to specify the thumbprint manually.

**Comment by amarzavery** [comment]
@colemickens - Just executing `azure login` basically without `-u <username|spn>` will always lead to device login. That is the desired behavior. I havent seen any authnetication mechanism in azure where the user can only provide a cert file and login.

ASM/RDFE mode (`azure config mode asm`) still authenticates using publish settings file. Are you referring to that?

`azure account download` - downloads the publishsettings file.
`azure account import <path to downloaded publish settings file>` will import the publish settings file and then you can execute commands in asm mode only.

After you have imported successfully you can also execute `azure account cert export` which exports a `.pem` file from your publish settings file.

**Comment by colemickens** [comment]
```shell
$ azure login \
    --certificate-file "/home/cole/publishing_management_certificates/RhelPublishingFairfax.pfx" \
    --thumbprint "8FA6F602FC101989BA3E8038E3177EE6C7904616" \
    --environment "AzureUSGovernment" \
    --tenant "usgovcloud.onmicrosoft.com" \
    --username "usgovcloud.onmicrosoft.com" \
    --password "usgovcloud.onmicrosoft.com"

[32minfo[39m:    Executing command [1mlogin[22m
[32minfo[39m:    Authenticating...
[31merror[39m:   Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50034: To sign into this application the account must be added to the usgovcloud.onmicrosoft.com directory.\r\nTrace ID: 8063ebd3-8a23-4b57-a4a3-58edf3b575c4\r\nCorrelation ID: a09a1f55-c25b-4b39-97a6-d62e600a2892\r\nTimestamp: 2016-10-16 00:33:57Z","error_codes":[50034],"timestamp":"2016-10-16 00:33:57Z","trace_id":"8063ebd3-8a23-4b57-a4a3-58edf3b575c4","correlation_id":"a09a1f55-c25b-4b39-97a6-d62e600a2892"}
[31merror[39m:   Error information has been recorded to /home/cole/.azure/azure.err
[31merror[39m:   [1mlogin[22m command [1m[31mfailed
[39m[22m
```

xplat-cli is supposed to be white-listed and accessible for all tenants, so why is it telling me the app needs to be registered to be able to login?

**Comment by colemickens** [comment]
Just got your reply @amarzavery thanks for the quick response...

I have manually onboarded a certificate and have converted the PFX to a PEM. Using publishsettings is not an option for sovereign clouds. I'm happily using this with `azurectl` with no problems, no need to specify thumbprint or tenant information. Xplat-cli seems broken here, or offering an less useful UX.

**Comment by colemickens** [comment]
>I havent seen any authnetication mechanism in azure where the user can only provide a cert file and login.

Yeah, my login to `azurectl` is two things: management cert, subscription id. No tenant information, no username, no password, no thumbprint. It's considerably easier and less confusing for the user.

**Comment by amarzavery** [comment]
@colemickens - I see. I am not aware about this scenario. We have tested org id user auth (non 2FA) and sp auth for German cloud. However, I dont remember testing the US Govt. cloud. I was told that it should work as the public cloud as far as the sp and non 2FA user auth is concerned.

Quick question: Have you tried the available standard options - user auth (org id) or sp auth ?

**Comment by colemickens** [comment]
Those aren't available to us because of hands-off in sovereign cloud. My only option is the management certificate. Like I said, `azurectl` works swimmingly so I feel like this is an xplat-cli problem.

**Comment by amarzavery** [comment]
@yugangw-msft, @markcowl  - are you aware about this scenario of login into US Govt. cloud?

**Comment by colemickens** [comment]
(For reference, here's how I'm logging into `azurectl`: )

```shell
$ azurectl setup account configure \
    --name 'default_account' \
    --management-pem-file '/tmp/tmp.6jMYdsd3ou' \
    --management-url 'https://management.core.usgovcloudapi.net/' \
    --subscription-id '46c8c963-04eb-42e0-8a2a-c383891bd430' \
    --storage-account-name 'rhelimage' \
    --container-name 'publish' \
    --region 'USGov Iowa'
```

**Comment by colemickens** [comment]
Another data point... logging in with PS seems to avoid tenants/aad in general, again showing that xplat-cli shouldn't be requiring these args. In fact, it's impossible to determine if `usgovcloud.onmicrosoft.com` is the correct tenant because when I login with a management cert to Powershell, it doesn't populate any Tenant information and there doesn't seem to be a way to query it. 😕 

Anyway, I'll wait to hear about how I'm supposed to be logging in or if this is a bug. Thanks again for looking at this @amarzavery on the weekend.

**Comment by ahmetalpbalkan** [comment]
You should be able to use just PEM+subscriptionID. The issue is not Fairfax specific to be accurate. The publishSettings file is basically just pfx+SubscriptionID which is the same thing. I think this is a bug/ux issue.

**Comment by yugangw-msft** [comment]
Under `ARM` mode, all login options go around the ADAL, which makes sense because ARM as a resource is a relying party on AAD. This explains:
1. If the `azure login` sees no `--username` parameter provided for a user or service principal, it assumes the device auth. Of course, the command should error about useless `--certificate-file FF.pem`, this is a bug.
2. Under `arm` mode `--thumbprint` and `--certificate-file` were introduced for login using a service principal with a certificate. There is a [end to end flow](https://github.com/Azure/azure-sdk-for-python/issues/811) I mentioned at Python-SDK you can refer, which could become one option you cna consider

So back to the fundamental question, can I login in w/o username? For `asm` which is certificate based, you can, but for `arm`, so far no.

@colemickens, once you login using `azurectl`, are you able to use arm command, say create a VM?
Also for PS, what command you tried? Was that for `arm`? Or `asm`? Let us know.

**Comment by colemickens** [comment]
I only need ASM support... `azurectl` is used for publishing images. But I fully expect I could have created ASM machines, yes. That's how auth works against ASM...

Anyway, seems like the SP login options could be suppressed when I'm in ASM mode? The answer seems to have been "You should use `azure account import` instead of `azure login --certificate-file`." 

I think @ahmetalpbalkan is right... so I made my own publishsettings file (took the PEM cert and formed the publishsettings file by hand) and then just ran into other various, previously reported issues: https://github.com/Azure/azure-xplat-cli/issues/718 https://github.com/Azure/azure-xplat-cli/issues/277

**Comment by yugangw-msft** [comment]
> Anyway, seems like the SP login options could be suppressed when I'm in ASM mode? The answer seems to have been "You should use azure account import instead of azure login --certificate-file."
Correct, this is a bug which cli should suppressed.

I also agreed @ahmetalpbalkan in principal, but i have never tried to cook the publishsettings file myself, particular of how to create a cert/key pair and upload the cert to azure

**Comment by ahmetalpbalkan** [comment]
I just wrote a simple program using the Azure SDK to work around this issue and get my task done. It looks like not many people are using PEM certs to authenticate to the CLI either based on the lack of the other issue reports. I guess this is a low-priority item.
