### ISSUE TITLE
Do not prompt for missing template parameters 

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-xplat-cli#3285]
CLI Version: **0.10.4**
OS Type: Linux
Installation via: docker

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure group deployment create` prompts for missing template parameters.

Steps to reproduce:
1) Have a template file `template.json` with parameters.
2) Then run `azure group deployment create --template-file template.json`

------

This behaviour is really not great for automated unattended scripts. Consider VSTS agent running a deployment and getting prompted there? There is nobody to reply to that prompt there.

The behaviour is probably due to this change: https://github.com/Azure/azure-xplat-cli/issues/2561

It would be very helpful if the CLI at least had a `--no-prompt` option and would exit with non-zero status code if any of the parameters were not supplied.

**Comment by amarzavery** [comment]
@ppanyukov - From version 0.10.3, we have introduced a new environment variable named "AZURE_NON_INTERACTIVE_MODE" when set will throw an error instead of prompting the user for an input.

You can find the list of environment variables supported by the CI over [here](https://github.com/Azure/azure-xplat-cli/blob/dev/Documentation/EnvironmentVariables.md#supported-environment-variables-for-using-the-cli).

Hope this resolves the issue.

**Comment by ppanyukov** [comment]
Yes thanks @amarzavery that env var will do, very handy doc too, should have looked there from the beginning :)

**Comment by atrauzzi** [comment]
@amarzavery This should just be a switch, not an environment variable.  Forcing people to spam their environment with things like this would get out of hand if every vendor took this approach.

Just have a `-q` flag for "quiet".
