### ISSUE TITLE
Support for Mobile Engagement App Collection?

### ISSUE THREAD

**Issue by lonombori** [Azure/azure-xplat-cli#3332]
Hello, is there a support for Mobile Engagement App Collection? I want to automate the adding of apps in Mobile Engagement. Thanks in advance.

**Comment by amarzavery** [comment]
@christav @matt-gibbs - Can you please respond to this feature request?

**Comment by guillaumekh** [comment]
I hope this belongs to the same issue:
```azure provider operations show "Microsoft.MobileEngagement/*``` gives the follwing error:
error:   Provider 'Microsoft.MobileEngagement' not found.
(w/ 0.10.7)

> @christav @matt-gibbs - Can you please respond to this feature request?

Does this mean azure-xplat-cli doe not support Mobile Engagement, and generally cannot be presumed to support _every_ Azure service ? I'm trying to create a custom role for a Mobile Engagement resource group, for which there is no web UI, and can only be done over CLI, powershell or REST API. I'm really not looking forward to having to do this over either of the two latter.. :/

**Comment by matt-gibbs** [comment]
@lonombori There aren't Mobile Engagement commands in the CLI. Automation still relies on calling the REST APIs directly.  https://msdn.microsoft.com/en-us/library/azure/mt683754.aspx
@guillaumekh Creating a custom role does not require service-specific commands. This article shows how to do it with the CLI. https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-control-manage-access-azure-cli

**Comment by guillaumekh** [comment]
@matt-gibbs I've read that article carefully. Please allow me to reformulate.

> There aren't Mobile Engagement commands in the CLI.

Does this also mean the CLI cannot be relied on to output the list of actions/operations related to Mobile Engagements ?

I'm insisting because this seems to create a situation where **one simply _cannot_ write a custom role for Mobile Engagements from CLI.**

Why?
In order to create a custom role, one needs to write a valid JSON and upload it with ```azure role create --inputfile <file path>```. That JSON looks like this:

```
{
    "Name": "Role name",
    "Description": "Role description",
    "Actions": [
        "<provider>/<resource>/<operation>",
        "Microsoft.Authorization/*/read", //example
        "Microsoft.Compute/virtualMachines/read" //example
        "Microsoft.Support/*" //example
    ],
    "NotActions": [],
    "AssignableScopes": ["/subscriptions/<subscription-id>"]
}
```

In order to write that JSON, one needs to find the names of the Azure _Actions_ to put in the role definition. This is done with ```azure provider operations show <providername>``` (e.g. ```azure provider operations show "Microsoft.Compute/*```) However it seems ```azure provider operations show "Microsoft.MobileEngagement/*``` is entirely unsupported.
