### ISSUE TITLE
Logging in with MSA+password

### ISSUE THREAD

**Issue by hanchoi** [Azure/azure-xplat-cli#3474]
CLI Version: newest
OS Type: Win
Installation via:  win-or-mac installer

Mode: ARM 

Environment: AzureCloud

Description:
"azure login -u user@outlook.com" command makes my partner type the password. And they got "Unauthorized Error". I'm sorry for not having the exact trace log but my question is below.

1. Is it impossible logging in with MSA+Password on Azure CLI?  
2. What are the limitations when logging in with MSA with global administrator privilege compared to AAD user?

**Comment by amarzavery** [comment]
@hanchoi - For interactive login, simply type `azure login` and press enter. The CLI should give you a link and access code. Oen the link in the browser and paste the code. Then the web page will ask you login using your creds, if successful the CLI will get the access token.

**Comment by hanchoi** [comment]
@amarzavery thank you for replying this. I think you mentioned login scenario 1 in this doc(https://docs.microsoft.com/en-us/azure/xplat-cli-connect) but my case is more related to scenario 2. I think scenario 2 could be the option when a developer wants to automate the login process.

**Comment by balajikris** [comment]
answering to the concern of "automate the login process", I would think `Scenario 3: azure login with a service principal` is more suited for automation purposes since there isn't a need to put in a password here. any reason that won't work for you?

**Comment by amarzavery** [comment]
Scenario2 works only for organizational accounts that do not have 2FA setup. In the original issue description, you have given an example where the user id is a live id (@outlook.com). Such accounts can be logged in only via interactive login.

For automation/scripting scenarios, as @balajikris mentioned, you need to follow scenario 3 (authentication via service principal /secret).

Creating a service principal and logging in as one is very simple. It can be achieved in 3 simple steps. Please read [this doc](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#2-via-xplatcli-in-3-simple-steps).

**Comment by hanchoi** [comment]
Thank you guys ! Your description helped me a lot so I'm clear now. I think there might be developers thinking in the same way.

**Comment by options** [comment]
@amarzavery @hanchoi It looks very strange and uncomfortable. As I login azure using powershell, it perfectly allow to login with id/password as text. but why auzre cli only has that restriction ? if that is microsoft recommendation, Powershell also wouldn't allow this method. And most of people want to know why this login step isnot recommneded. 
As Users perspective, this limitation looks like inconsisent and abnormal.
Myung

**Comment by amarzavery** [comment]
I am not able to understand your concern.
xplat cli supports 3 modes of login
- login with username and password (works only for organizational Ids that are not 2FA enabled) `azure login -u $username`
- interactive login where the CLI emits a url and access code and the user authenticates in the browser `azure login`
   - the interactive login experience is different from powershell because in powershell with .net support it can pop up a UI where the user can provide username and password. With Xplat CLI this cannot be done in cmd/bash on all platforms. So we provide interactive login
- service-principal login (useful for automation) `azure login --service-principal -u <$clientId/SPN> -p <$secret> --tenant <$tenantId>`

The first and third are same in powershell and CLI. For 2nd the experience is different and I have explained the reasons for it.
