### ISSUE TITLE
azure login -u confusion: MS Personal vs Work accounts

### ISSUE THREAD

**Issue by mmalyj** [Azure/azure-xplat-cli#3522]
I am trying to use azure cli to create a VM from a VHD file I uploaded to Azure, as described in https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-classic-create-upload-vhd. When I try logging with 

PS> azure login -u marko@mycompany.com

When I supply the password, I get this error:
_Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password_

I just figured out that I have TWO Microsoft accounts named marko@mycompany.com, a "Personal" account that I set up years ago, and a "Work" account that my company set up (without telling me) which uses the Microsoft anti-spam cloud service. This turns out to be typical, as you can see from this article https://support.microsoft.com/en-us/help/11545/microsoft-account-rename-your-personal-account

When I repeat the above command, and supply my Work account password instead of my Personal account password, I get 
_\info:    No subscriptions found for this account
info:    login command OK_

This tells me that "azure login" is only picking up the presence of my Work account. I need it to login to my Personal account, which is where my Azure is located.

Can you guys create a flag in the "azure login" command line that will allow us to specify that the "-u" account supplied is a Personal account, or else a Work account?

CLI Version: 0.10.9
OS Type: Win
Installation via:  win-or-mac installer
Environment: AzureCloud

**Comment by balajikris** [comment]
I may not be accurate here, but if you're completely blocked on signing in with your personal account, I'd like to suggest an approach to see if that works -

Can you try simply `azure login`  without the -u. However, this would only work if your personal account supports 2 factor authentication. My guess is, since this flow needs to be completed by signing in via a browser, you may have an option to choose your personal account instead of the work account..

I'm not even sure if that would work, but suggesting so you could perhaps give it a shot.

**Comment by amarzavery** [comment]
@balajikris is right. The usecase is very simple.
- If your account is 2FA enabled or is a live account (@outlook.com, @gmail.com, @live.com, etc.) then you need to use interactive login `azure login`
- In all the scenarios except the above one use `azure login -u <username>`.

**Comment by mmalyj** [comment]
My Personal account is a live account, so 2FA worked for me with just "azure login" without the -u. Thanks!
