### ISSUE TITLE
Extracting xplat-cli as general purpose nodejs tab-completion library

### ISSUE THREAD

**Issue by jonathankarsh** [Azure/azure-xplat-cli#3667]
Hey,
Thanks for putting together this project, it's neat!
I'm looking at the tab-completion part of this tool and is seems that there's a significant investment in combining [Omelette](https://github.com/f/omelette) and [Commander.js](https://github.com/tj/commander.js). The quick access into a plugins.json file is particularly interesting and (I'm sure) makes for easy iterations for new added commands.

I wanted to know if you'd be interested in pushing the tab completion component to an external repo. As a JS developer I would love to have a well organised API to both describe the commands a CLI supports, and also having it auto-installed (or at least, single command installed). I don't think the npm universe at this point in time gives a good solution to both of these, so there's a nice opportunity/need here.

Cheers
Jonathan

**Comment by jonathankarsh** [comment]
Noticing https://github.com/Azure/azure-xplat-cli/issues/3556 just now, looks like a decision is hanging in the air for this project, in that https://github.com/Azure/azure-cli/ might eventually take its place.
I'm hoping that things will change and it doesn't happen, but if this project is destined to be deprecated, I believe there's even a stronger case for making parts of this repo useful for other purposes.

**Comment by jonathankarsh** [comment]
@amarzavery any opinions about this one?
Would be great to hear your thoughts.

**Comment by amarzavery** [comment]
@jonathankarsh - This project is pretty much deprecated. The new cli written in python is the azure cli. I love the idea of combining Omelette and Commander. It would be a useful product. 

However, have you seen another package called [yargs](https://github.com/yargs/yargs). I think it is way better than commander and has already solved [tab completion](https://github.com/yargs/yargs/blob/master/docs/api.md#completioncmd-description-fn) (although only for bash). It is pretty decent. I have used it in some other projects like `oav` (A command line tool that performs semantic and model validation for a given swagger spec and much more). `yargs` supports a design where you can organize all your commands in a folder like [this](https://github.com/Azure/oav/tree/master/lib/commands) and have a startup file named [cli.ts](https://github.com/Azure/oav/blob/master/cli.ts). Intellisense and type checking because of typescript while developing the commands is even better.

**Comment by jonathankarsh** [comment]
Thanks @amarzavery! yargs looks pretty cool, I'll try it out :-)

Sounds great. I might give the Omelette-Commander a go soon depending on other commitments.
Cheers!
