### ISSUE TITLE
OpenSSL - PFX not work

### ISSUE THREAD

**Issue by tuyen-vuduc** [Azure/azure-xplat-cli#3694]
I tried to follow [this guide](https://github.com/Azure/azure-xplat-cli/wiki/Getting-Self-Signed-SSL-Certificates-(.pem-and-.pfx)) to generate a PFX key to enable my site SSL.

However, I always get error when trying to use it for my website.

```
Failed to add SSL binding. The certificate with thumbprint 'B65EA5ED6534A4233257062EE7F13E89701C643E' is invalid for SSL. The Enhanced Key Usage must be present and must contain Server Authentication (1.3.6.1.5.5.7.3.1).
```

I am on a Mac with OpenSSL

**Comment by devoto13** [comment]
@tuyen-vuduc You'll need to add this extension to your certificate explicitly. If you use OpenSSL 1.1.1+ than you can use below command to generate the certificate instead of one provided in the linked guide:

    $ openssl req -x509 -new -key my.key -out my.cer -addext "extendedKeyUsage=serverAuth"

And check [this answer](https://serverfault.com/a/573038/236787) for more details and solution for OpenSSL <1.1.1.
